inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/internal/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/sufia/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# catalog_controller.rb is usually long because it is mostly configuration
# user.rb could use some refactoring, see #249
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/SymbolProc: # https://github.com/bbatsov/rubocop/issues/3071
  Exclude:
    - 'app/models/sufia/uploaded_file.rb'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $in_travis

Style/SingleLineBlockParams:
  Enabled: false

Rails:
  Enabled: true
