# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || "http://127.0.0.1:8983/solr/hydra-development" %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8985/solr/hydra-test" %>
production:
  url: http://your.production.server:8080/bl_solr/core0
